name: HW2-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint with Pylint and AutoPEP8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install pylint autopep8 radon pytest

    - name: Run AutoPEP8
      run: |
        autopep8 --in-place --aggressive --aggressive *.py
        git diff --exit-code

    - name: Run Pylint
      run: pylint *.py

    - name: Run Radon
      run: radon cc *.py --total-average

  test:
    name: Test with Pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run Pytest
      run: pytest